spring:
  application:
    name: b3-testes-exercicios
  datasource.driver-class-name: org.h2.Driver
  datasource.url: jdbc:h2:mem:test
  datasource.username: sa
  datasource.password:
  h2.console.enabled: true
  h2.console.path: /h2
  jpa:
    hibernate.ddl-auto: create
    show-sql: true